# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f910dbe74e7a77bcb4caa4e61cf01bf64817eaaadfe739738e3cd08bab73442be5a36e8661b4d97db0fb93bc491da388bb0bd6b52f8264f90e72e00da4cf28e

test:
  secret_key_base: a7f814a915d34fcd8d9d0db92a23ed160c2b2edb1a331c34edfb0f0bac1ba794b12998dbc5765e3a5fdcb6975bafb615b79a03faed8f07ff3aa1ac90ce755cff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
